apiVersion: v1
kind: ConfigMap
metadata:
  name: hbase-krbconf-configmap
  namespace: stagging
data:
  krb5.conf: |
    
    [libdefaults]
      forwardable = true
      default_realm = EXAMPLE.COM
      ticket_lifetime = 24h
      dns_lookup_realm = false
      dns_lookup_kdc = false
      default_ccache_name = /tmp/krb5cc_%{uid}
      #default_tgs_enctypes = aes des3-cbc-sha1 rc4 des-cbc-md5
      #default_tkt_enctypes = aes des3-cbc-sha1 rc4 des-cbc-md5

    [logging]
      default = FILE:/var/log/krb5kdc.log
      admin_server = FILE:/var/log/kadmind.log
      kdc = FILE:/var/log/krb5kdc.log

    [realms]
      EXAMPLE.COM = {
         admin_server = 192.168.1.53
         kdc = 192.168.1.53
      }