apiVersion: v1
kind: ConfigMap
metadata:
  name: web-app-cm
  namespace: r8-stagging
data:
  config.js: |
    /** Common configuration **/
    const CONFIG = {
      CERT: "airlinq_com.crt", // Certificate file name
      KEY: "airlinq.key", // Certificate key file name
      WEB_APP_PORT: 8082,
      NODE_API_URL: "https://192.168.1.42:8083/",
      API_URL: "https://i.airlinq.com:8019/",
      // Google tag manager key for showing analytics on Google Analytics
      GOOGLE_TAG_MANAGER_KEY: "GTM-5RVZHQH"
    };
    module.exports = CONFIG;
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: r8-stagging
spec:
  ports:
  -
    name: web-port
    protocol: TCP
    port: 8082
    targetPort: 8082
  selector:
    app: r8-WebApp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: r8-web-deployment
  namespace: r8-stagging
  labels:
    app: r8-WebApp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: r8-WebApp
  template:
    metadata:
      labels:
        app: r8-WebApp
    spec:
      imagePullSecrets:
      -
        name: git-image-pull-secret
      containers:
      -
        image: "ghcr.io/peeyush-tm/gcontrol-ui-react/cmp-ui-react:3.9.4.0"
        name: web-app
        ports:
        -
          name: ui-port
          containerPort: 8082 
        readinessProbe:
          httpGet:
            path: /
            port: 8082
            scheme: HTTPS
          initialDelaySeconds: 100
          periodSeconds: 20
          timeoutSeconds: 2
        volumeMounts:
        -
          name: web-cm-volume
          mountPath: /reactapp/config.js
          subPath: config.js
      volumes:
      -
        name: web-cm-volume
        configMap:
          name: web-app-cm
---
apiVersion: v1
kind: Service
metadata:
  name: web-expose-service
  namespace: r8-stagging
spec:
  type: NodePort
  ports:
  -
    name: web-port
    protocol: TCP
    port: 8082
    targetPort: 8082
  selector:
    app: r8-WebApp